package disasm

import (
	"errors"
)

// Instruction Set
//////////////////////////////////////

// Returns the first one line instruction in the form of an Instruction "struct" of a byte array that we are given
func Parse(in []byte) (Instruction, error) {
	firstByte := in[0]
	var signed bool

	// Check if this is a signed operation
	if firstByte == 0xFE {
		signed = true
		firstByte = in[1]
	}

	if instruction, ok := instructions[firstByte]; ok {
		// We have it!
		instruction.Signed = signed

		// Check for Indexed Addressing Mode Instruction Type
		if instruction.AddressingMode == "indexed" && instruction.VariableLength == true {
			if in[1]&1 == 1 {
				instruction.ByteLength++
				instruction.AddressingMode = "long-indexed"
			} else {
				instruction.AddressingMode = "short-indexed"
			}
		}

		// Check for Indirect Addressing Mode Instruction Type
		if instruction.AddressingMode == "indirect" {
			if in[1]&1 == 1 {
				instruction.AddressingMode = "indirect+"
				instruction.AutoIncrement = true
			}
		}

		// Add in our Reference string
		instruction.AddrModeRef = addrModeRef[instruction.AddressingMode][instruction.OperandCount]

		// Adjust for signed instructions
		if signed {
			instruction.ByteLength++
			instruction.Signed = signed
			instruction.Mnemonic = "Signed " + instruction.Mnemonic
		}

		instruction.Raw = in[0:instruction.ByteLength]

		return instruction, nil

	} else {
		return Instruction{ByteLength: 1}, errors.New("Unable to find instruction!")
	}

}

type Instruction struct {
	Address        int
	Raw            []byte
	Mnemonic       string
	Operands       []byte
	ByteLength     int
	OperandCount   int
	AddressingMode string
	AddrModeRef    []string
	Description    string
	VariableLength bool
	AutoIncrement  bool
	Flags          Flags
	Signed         bool
	Ignore         bool
	Reserved       bool
}

type OperandType struct {
	Description string
	Bits        int
}

var operandTypes = map[string]OperandType{
	"aa": {
		Description: "A 2-bit field within an opcode that selects the basic addressing mode used. This field is present only in those opcodes that allow addressing mode options. ",
		Bits:        2,
	},
	"baop": {
		Description: "A byte operand that is addressed by any addressing mode.",
		Bits:        8,
	},
	"bbb": {
		Description: "A 3-bit field within an opcode that selects a specific bit within a register.",
		Bits:        3,
	},
	"bitno": {
		Description: "A 3-bit field within an opcode that selects one of the eight bits in a byte. ",
		Bits:        3,
	},
	"breg": {
		Description: "A byte register in the internal register file. When it could be unclear whether this variable refers to a source or a destination register, it is prefixed with an S or a D. The value must be in the range of 00–FFH.",
		Bits:        8,
	},
	"cadd": {
		Description: " An address in the program code",
		//Bits:       0,
	},
	"Dbreg": {
		Description: "A byte register in the lower register file that serves as the destination of the instruction operation. ",
		Bits:        8,
	},
	"disp": {
		Description: "Displacement. The distance between the end of an instruction and the target label.",
		//Bits:       0,
	},
	"Dlreg": {
		Description: "A 32-bit register in the lower register file that serves as the destination of the instruction operation. Must be aligned on an address that is evenly divisible by 4. The value must be in the range of 00–FCH.",
		Bits:        8,
	},
	"Dwreg": {
		Description: "A word register in the lower register file that serves as the destination of the instruction operation. Must be aligned on an address that is evenly divisible by 2. The value must be in the range of 00–FEH.",
		Bits:        8,
	},
	"lreg": {
		Description: "A 32-bit register in the lower register file. Must be aligned on an address that is evenly divisible by 4. The value must be in the range of 00–FCH. ",
		Bits:        8,
	},
	"ptr2_reg": {
		Description: " A double-pointer register, used with the EBMOVI instruction. Must be aligned on an address that is evenly divisible by 8. The value must be in the range of 00–F8H. ",
		Bits:        8,
	},
	"preg": {
		Description: "A pointer register. Must be aligned on an address that is evenly divisible by 4. The value must be in the range of 00–FCH. ",
		Bits:        8,
	},
	"Sbreg": {
		Description: "A byte register in the lower register file that serves as the source of the instruction operation.",
		Bits:        8,
	},
	"Slreg": {
		Description: "A 32-bit register in the lower register file that serves as the source of the instruction operation. Must be aligned on an address that is evenly divisible by 4. The value must be in the range of 00–FCH.",
		Bits:        8,
	},
	"Swreg": {
		Description: "A word register in the lower register file that serves as the source of the instruction operation. Must be aligned on an address that is evenly divisible by 2. The value must be in the range of 00–FEH.",
		Bits:        8,
	},
	"treg": {
		Description: "A 24-bit register in the lower register file. Must be aligned on an address that is evenly divisible by 4. The value must be in the range of 00–FCH.",
		Bits:        8,
	},
	"waop": {
		Description: "A word operand that is addressed by any addressing mode.",
		Bits:        16,
	},
	"w2_reg": {
		Description: "A double-word register in the lower register file. Must be aligned on an address that is evenly divisible by 4. The value must be in the range of 00–FCH. Although w2_reg is similar to lreg, there is a distinction: w2_reg consists of two halves, each containing a 16-bit address; lreg is indivisible and contains a 32-bit number.",
		//Bits:       0,
	},
	"wreg": {
		Description: "A word register in the lower register file. When it could be unclear whether this variable refers to a source or a destination register, it is prefixed with an S or a D. Must be aligned on an address that is evenly divisible by 2. The value must be in the range of 00–FEH.",
		//Bits:       0,
	},
	"xxx": {
		Description: "The three high-order bits of displacement",
		Bits:        3,
	},
}

var addrModeRef = map[string]map[int][]string{
	// mode -> op count -> reference string
	"direct": {
		1: {"Dest or Src1"},
		2: {"Dest", "Src1"},
		3: {"Dest", "Src1", "Src2"},
	},
	"indirect": {
		1: {"[addr]"},
		2: {"Dest", "[addr]"},
		3: {"Dest", "Src1", "[addr]"},
	},
	"indirect+": {
		1: {"[addr]+"},
		2: {"Dest", "[addr]+"},
		3: {"Dest", "Src1", "[addr]+"},
	},
	"immediate": {
		1: {"#value"},
		2: {"Dest", "#value"},
		3: {"Dest", "Src1", "#value"},
	},
	"indexed": {
		1: {"Dest or Src1"},
		2: {"Dest", "offs[addr]"},
		3: {"Dest", "Src1", "offs[addr]"},
	},
	"short-indexed": {
		1: {"Dest or Src1"},
		2: {"Dest", "offs[addr]"},
		3: {"Dest", "Src1", "offs[addr]"},
	},
	"long-indexed": {
		1: {"Dest or Src1"},
		2: {"Dest", "offs[addr]"},
		3: {"Dest", "Src1", "offs[addr]"},
	},
}

type Flags struct{}

var instructions = map[byte]Instruction{
	0x00: Instruction{
		Mnemonic:       "SKIP",
		ByteLength:     2,
		OperandCount:   0,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         true,
		Signed:         false,
		Reserved:       false,
	},
	0x01: Instruction{
		Mnemonic:       "CLR",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x02: Instruction{
		Mnemonic:       "NOT",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x03: Instruction{
		Mnemonic:       "NEG",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x04: Instruction{
		Mnemonic:       "XCH",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x05: Instruction{
		Mnemonic:       "DEC",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x06: Instruction{
		Mnemonic:       "EXT",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x07: Instruction{
		Mnemonic:       "INC",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x08: Instruction{
		Mnemonic:       "SHR",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x09: Instruction{
		Mnemonic:       "SHL",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x0A: Instruction{
		Mnemonic:       "SHRA",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x0B: Instruction{
		Mnemonic:       "XCH",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x0C: Instruction{
		Mnemonic:       "SHRL",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x0D: Instruction{
		Mnemonic:       "SHLL",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x0E: Instruction{
		Mnemonic:       "SHRAL",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x0F: Instruction{
		Mnemonic:       "NORML",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x10: Instruction{
		Mnemonic:   "Reserved",
		ByteLength: 1,
		Reserved:   true,
	},
	0x11: Instruction{
		Mnemonic:       "CLRB",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x12: Instruction{
		Mnemonic:       "NOTB",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x13: Instruction{
		Mnemonic:       "NEGB",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x14: Instruction{
		Mnemonic:       "XCHB",
		ByteLength:     2,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x15: Instruction{
		Mnemonic:       "DECB",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x16: Instruction{
		Mnemonic:       "EXTB",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x17: Instruction{
		Mnemonic:       "INCB",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x18: Instruction{
		Mnemonic:       "SHRB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x19: Instruction{
		Mnemonic:       "SHLB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x1A: Instruction{
		Mnemonic:       "SHRAB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x1B: Instruction{
		Mnemonic:       "XCHB",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x1C: Instruction{
		Mnemonic:       "EST",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x1D: Instruction{
		Mnemonic:       "EST",
		ByteLength:     6,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x1E: Instruction{
		Mnemonic:       "ESTB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x1F: Instruction{
		Mnemonic:       "ESTB",
		ByteLength:     6,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x20: Instruction{
		Mnemonic:       "SJMP",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x21: Instruction{
		Mnemonic:       "SJMP",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x22: Instruction{
		Mnemonic:       "SJMP",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x23: Instruction{
		Mnemonic:       "SJMP",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x24: Instruction{
		Mnemonic:       "SJMP",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x25: Instruction{
		Mnemonic:       "SJMP",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x26: Instruction{
		Mnemonic:       "SJMP",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x27: Instruction{
		Mnemonic:       "SJMP",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x28: Instruction{
		Mnemonic:       "SCALL",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x29: Instruction{
		Mnemonic:       "SCALL",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x2A: Instruction{
		Mnemonic:       "SCALL",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x2B: Instruction{
		Mnemonic:       "SCALL",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x2C: Instruction{
		Mnemonic:       "SCALL",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x2D: Instruction{
		Mnemonic:       "SCALL",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x2E: Instruction{
		Mnemonic:       "SCALL",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x2F: Instruction{
		Mnemonic:       "SCALL",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x30: Instruction{
		Mnemonic:       "JBC",
		ByteLength:     3,
		OperandCount:   3,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x31: Instruction{
		Mnemonic:       "JBC",
		ByteLength:     3,
		OperandCount:   3,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x32: Instruction{
		Mnemonic:       "JBC",
		ByteLength:     3,
		OperandCount:   3,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x33: Instruction{
		Mnemonic:       "JBC",
		ByteLength:     3,
		OperandCount:   3,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x34: Instruction{
		Mnemonic:       "JBC",
		ByteLength:     3,
		OperandCount:   3,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x35: Instruction{
		Mnemonic:       "JBC",
		ByteLength:     3,
		OperandCount:   3,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x36: Instruction{
		Mnemonic:       "JBC",
		ByteLength:     3,
		OperandCount:   3,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x37: Instruction{
		Mnemonic:       "JBC",
		ByteLength:     3,
		OperandCount:   3,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x38: Instruction{
		Mnemonic:       "JBS",
		ByteLength:     3,
		OperandCount:   3,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x39: Instruction{
		Mnemonic:       "JBS",
		ByteLength:     3,
		OperandCount:   3,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x3A: Instruction{
		Mnemonic:       "JBS",
		ByteLength:     3,
		OperandCount:   3,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x3B: Instruction{
		Mnemonic:       "JBS",
		ByteLength:     3,
		OperandCount:   3,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x3C: Instruction{
		Mnemonic:       "JBS",
		ByteLength:     3,
		OperandCount:   3,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x3D: Instruction{
		Mnemonic:       "JBS",
		ByteLength:     3,
		OperandCount:   3,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x3E: Instruction{
		Mnemonic:       "JBS",
		ByteLength:     3,
		OperandCount:   3,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x3F: Instruction{
		Mnemonic:       "JBS",
		ByteLength:     3,
		OperandCount:   3,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x40: Instruction{
		Mnemonic:       "AND",
		ByteLength:     4,
		OperandCount:   3,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x41: Instruction{
		Mnemonic:       "AND",
		ByteLength:     5,
		OperandCount:   3,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x42: Instruction{
		Mnemonic:       "AND",
		ByteLength:     4,
		OperandCount:   3,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x43: Instruction{
		Mnemonic:       "AND",
		ByteLength:     5,
		OperandCount:   3,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x44: Instruction{
		Mnemonic:       "ADD",
		ByteLength:     4,
		OperandCount:   3,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x45: Instruction{
		Mnemonic:       "ADD",
		ByteLength:     5,
		OperandCount:   3,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x46: Instruction{
		Mnemonic:       "ADD",
		ByteLength:     4,
		OperandCount:   3,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x47: Instruction{
		Mnemonic:       "ADD",
		ByteLength:     5,
		OperandCount:   3,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x48: Instruction{
		Mnemonic:       "SUB",
		ByteLength:     4,
		OperandCount:   3,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x49: Instruction{
		Mnemonic:       "SUB",
		ByteLength:     5,
		OperandCount:   3,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x4A: Instruction{
		Mnemonic:       "SUB",
		ByteLength:     4,
		OperandCount:   3,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x4B: Instruction{
		Mnemonic:       "SUB",
		ByteLength:     5,
		OperandCount:   3,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x4C: Instruction{
		Mnemonic:       "MULU",
		ByteLength:     4,
		OperandCount:   3,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x4D: Instruction{
		Mnemonic:       "MULU",
		ByteLength:     5,
		OperandCount:   3,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x4E: Instruction{
		Mnemonic:       "MULU",
		ByteLength:     4,
		OperandCount:   3,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x4F: Instruction{
		Mnemonic:       "MULU",
		ByteLength:     5,
		OperandCount:   3,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x50: Instruction{
		Mnemonic:       "ANDB",
		ByteLength:     4,
		OperandCount:   3,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x51: Instruction{
		Mnemonic:       "ANDB",
		ByteLength:     4,
		OperandCount:   3,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x52: Instruction{
		Mnemonic:       "ANDB",
		ByteLength:     4,
		OperandCount:   3,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x53: Instruction{
		Mnemonic:       "ANDB",
		ByteLength:     5,
		OperandCount:   3,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x54: Instruction{
		Mnemonic:       "ADDB",
		ByteLength:     4,
		OperandCount:   3,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x55: Instruction{
		Mnemonic:       "ADDB",
		ByteLength:     4,
		OperandCount:   3,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x56: Instruction{
		Mnemonic:       "ADDB",
		ByteLength:     4,
		OperandCount:   3,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x57: Instruction{
		Mnemonic:       "ADDB",
		ByteLength:     5,
		OperandCount:   3,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x58: Instruction{
		Mnemonic:       "SUBB",
		ByteLength:     4,
		OperandCount:   3,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x59: Instruction{
		Mnemonic:       "SUBB",
		ByteLength:     4,
		OperandCount:   3,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x5A: Instruction{
		Mnemonic:       "SUBB",
		ByteLength:     4,
		OperandCount:   3,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x5B: Instruction{
		Mnemonic:       "SUBB",
		ByteLength:     5,
		OperandCount:   3,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x5C: Instruction{
		Mnemonic:       "MULUB",
		ByteLength:     4,
		OperandCount:   3,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x5D: Instruction{
		Mnemonic:       "MULUB",
		ByteLength:     4,
		OperandCount:   3,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x5E: Instruction{
		Mnemonic:       "MULUB",
		ByteLength:     4,
		OperandCount:   3,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x5F: Instruction{
		Mnemonic:       "MULUB",
		ByteLength:     5,
		OperandCount:   3,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x60: Instruction{
		Mnemonic:       "AND",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x61: Instruction{
		Mnemonic:       "AND",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x62: Instruction{
		Mnemonic:       "AND",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x63: Instruction{
		Mnemonic:       "AND",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x64: Instruction{
		Mnemonic:       "ADD",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x65: Instruction{
		Mnemonic:       "ADD",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x66: Instruction{
		Mnemonic:       "ADD",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x67: Instruction{
		Mnemonic:       "ADD",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x68: Instruction{
		Mnemonic:       "SUB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x69: Instruction{
		Mnemonic:       "SUB",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x6A: Instruction{
		Mnemonic:       "SUB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x6B: Instruction{
		Mnemonic:       "SUB",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x6C: Instruction{
		Mnemonic:       "MULU",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x6D: Instruction{
		Mnemonic:       "MULU",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x6E: Instruction{
		Mnemonic:       "MULU",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x6F: Instruction{
		Mnemonic:       "MULU",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x70: Instruction{
		Mnemonic:       "ANDB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x71: Instruction{
		Mnemonic:       "ANDB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x72: Instruction{
		Mnemonic:       "ANDB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x73: Instruction{
		Mnemonic:       "ANDB",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x74: Instruction{
		Mnemonic:       "ADDB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x75: Instruction{
		Mnemonic:       "ADDB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x76: Instruction{
		Mnemonic:       "ADDB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x77: Instruction{
		Mnemonic:       "ADDB",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x78: Instruction{
		Mnemonic:       "SUBB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x79: Instruction{
		Mnemonic:       "SUBB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x7A: Instruction{
		Mnemonic:       "SUBB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x7B: Instruction{
		Mnemonic:       "SUBB",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x7C: Instruction{
		Mnemonic:       "MULUB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x7D: Instruction{
		Mnemonic:       "MULUB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x7E: Instruction{
		Mnemonic:       "MULUB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x7F: Instruction{
		Mnemonic:       "MULUB",
		ByteLength:     5,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x80: Instruction{
		Mnemonic:       "OR",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x81: Instruction{
		Mnemonic:       "OR",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x82: Instruction{
		Mnemonic:       "OR",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x83: Instruction{
		Mnemonic:       "OR",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x84: Instruction{
		Mnemonic:       "XOR",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x85: Instruction{
		Mnemonic:       "XOR",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x86: Instruction{
		Mnemonic:       "XOR",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x87: Instruction{
		Mnemonic:       "XOR",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x88: Instruction{
		Mnemonic:       "CMP",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x89: Instruction{
		Mnemonic:       "CMP",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x8A: Instruction{
		Mnemonic:       "CMP",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x8B: Instruction{
		Mnemonic:       "CMP",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x8C: Instruction{
		Mnemonic:       "DIVU",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x8D: Instruction{
		Mnemonic:       "DIVU",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x8E: Instruction{
		Mnemonic:       "DIVU",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x8F: Instruction{
		Mnemonic:       "DIVU",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x90: Instruction{
		Mnemonic:       "ORB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x91: Instruction{
		Mnemonic:       "ORB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x92: Instruction{
		Mnemonic:       "ORB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x93: Instruction{
		Mnemonic:       "ORB",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x94: Instruction{
		Mnemonic:       "XORB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x95: Instruction{
		Mnemonic:       "XORB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x96: Instruction{
		Mnemonic:       "XORB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x97: Instruction{
		Mnemonic:       "XORB",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x98: Instruction{
		Mnemonic:       "CMPB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x99: Instruction{
		Mnemonic:       "CMPB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x9A: Instruction{
		Mnemonic:       "CMPB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x9B: Instruction{
		Mnemonic:       "CMPB",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x9C: Instruction{
		Mnemonic:       "DIVUB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x9D: Instruction{
		Mnemonic:       "DIVUB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x9E: Instruction{
		Mnemonic:       "DIVUB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x9F: Instruction{
		Mnemonic:       "DIVUB",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xA0: Instruction{
		Mnemonic:       "LD",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xA1: Instruction{
		Mnemonic:       "LD",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xA2: Instruction{
		Mnemonic:       "LD",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xA3: Instruction{
		Mnemonic:       "LD",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xA4: Instruction{
		Mnemonic:       "ADDC",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xA5: Instruction{
		Mnemonic:       "ADDC",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xA6: Instruction{
		Mnemonic:       "ADDC",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xA7: Instruction{
		Mnemonic:       "ADDC",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xA8: Instruction{
		Mnemonic:       "SUBC",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xA9: Instruction{
		Mnemonic:       "SUBC",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xAA: Instruction{
		Mnemonic:       "SUBC",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xAB: Instruction{
		Mnemonic:       "SUBC",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xAC: Instruction{
		Mnemonic:       "LDBZE",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xAD: Instruction{
		Mnemonic:       "LDBZE",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xAE: Instruction{
		Mnemonic:       "LDBZE",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xAF: Instruction{
		Mnemonic:       "LDBZE",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xB0: Instruction{
		Mnemonic:       "LDB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xB1: Instruction{
		Mnemonic:       "LDB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xB2: Instruction{
		Mnemonic:       "LDB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xB3: Instruction{
		Mnemonic:       "LDB",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xB4: Instruction{
		Mnemonic:       "ADDCB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xB5: Instruction{
		Mnemonic:       "ADDCB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xB6: Instruction{
		Mnemonic:       "ADDCB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xB7: Instruction{
		Mnemonic:       "ADDCB",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xB8: Instruction{
		Mnemonic:       "SUBCB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xB9: Instruction{
		Mnemonic:       "SUBCB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xBA: Instruction{
		Mnemonic:       "SUBCB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xBB: Instruction{
		Mnemonic:       "SUBCB",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xBC: Instruction{
		Mnemonic:       "LDBSE",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xBD: Instruction{
		Mnemonic:       "LDBSE",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xBE: Instruction{
		Mnemonic:       "LDBSE",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xBF: Instruction{
		Mnemonic:       "LDBSE",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xC0: Instruction{
		Mnemonic:       "ST",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xC1: Instruction{
		Mnemonic:       "BMOV",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xC2: Instruction{
		Mnemonic:       "ST",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xC3: Instruction{
		Mnemonic:       "ST",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xC4: Instruction{
		Mnemonic:       "STB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xC5: Instruction{
		Mnemonic:       "CMPL",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xC6: Instruction{
		Mnemonic:       "STB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xC7: Instruction{
		Mnemonic:       "STB",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xC8: Instruction{
		Mnemonic:       "PUSH",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xC9: Instruction{
		Mnemonic:       "PUSH",
		ByteLength:     3,
		OperandCount:   1,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xCA: Instruction{
		Mnemonic:       "PUSH",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xCB: Instruction{
		Mnemonic:       "PUSH",
		ByteLength:     3,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xCC: Instruction{
		Mnemonic:       "POP",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xCD: Instruction{
		Mnemonic:       "BMOVI",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xCE: Instruction{
		Mnemonic:       "POP",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xCF: Instruction{
		Mnemonic:       "POP",
		ByteLength:     3,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xD0: Instruction{
		Mnemonic:       "JNST",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xD1: Instruction{
		Mnemonic:       "JNH",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xD2: Instruction{
		Mnemonic:       "JGT",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xD3: Instruction{
		Mnemonic:       "JNC",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xD4: Instruction{
		Mnemonic:       "JNVT",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xD5: Instruction{
		Mnemonic:       "JNV",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xD6: Instruction{
		Mnemonic:       "JGE",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xD7: Instruction{
		Mnemonic:       "JNE",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xD8: Instruction{
		Mnemonic:       "JST",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xD9: Instruction{
		Mnemonic:       "JH",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xDA: Instruction{
		Mnemonic:       "JLE",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xDB: Instruction{
		Mnemonic:       "JC",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xDC: Instruction{
		Mnemonic:       "JVT",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xDD: Instruction{
		Mnemonic:       "JV",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xDE: Instruction{
		Mnemonic:       "JLT",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xDF: Instruction{
		Mnemonic:       "JE",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xE0: Instruction{
		Mnemonic:       "DJNZ",
		ByteLength:     3,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xE1: Instruction{
		Mnemonic:       "DJNZW",
		ByteLength:     3,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xE2: Instruction{
		Mnemonic:       "TIJMP",
		ByteLength:     4,
		OperandCount:   3,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xE3: Instruction{
		Mnemonic:       "EBR",
		ByteLength:     2,
		OperandCount:   1,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xE4: Instruction{
		Mnemonic:       "EBMOVI",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xE5: Instruction{
		Mnemonic:   "Reserved",
		ByteLength: 1,
		Reserved:   true,
	},
	0xE6: Instruction{
		Mnemonic:       "EJMP",
		ByteLength:     4,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xE7: Instruction{
		Mnemonic:       "LJMP",
		ByteLength:     3,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xE8: Instruction{
		Mnemonic:       "ELD",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xE9: Instruction{
		Mnemonic:       "ELD",
		ByteLength:     6,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xEA: Instruction{
		Mnemonic:       "ELDB",
		ByteLength:     3,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xEB: Instruction{
		Mnemonic:       "ELDB",
		ByteLength:     6,
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xEC: Instruction{
		Mnemonic:       "DPTS",
		ByteLength:     1,
		OperandCount:   0,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xED: Instruction{
		Mnemonic:       "EPTS",
		ByteLength:     1,
		OperandCount:   0,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xEE: Instruction{
		Mnemonic:   "Reserved",
		ByteLength: 1,
		Reserved:   true,
	},
	0xEF: Instruction{
		Mnemonic:       "LCALL",
		ByteLength:     3,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xF0: Instruction{
		Mnemonic:       "RET",
		ByteLength:     1,
		OperandCount:   0,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xF1: Instruction{
		Mnemonic:       "ECALL",
		ByteLength:     4,
		OperandCount:   1,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xF2: Instruction{
		Mnemonic:       "PUSHF",
		ByteLength:     1,
		OperandCount:   0,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xF3: Instruction{
		Mnemonic:       "POPF",
		ByteLength:     1,
		OperandCount:   0,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xF4: Instruction{
		Mnemonic:       "PUSHA",
		ByteLength:     1,
		OperandCount:   0,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xF5: Instruction{
		Mnemonic:       "POPA",
		ByteLength:     1,
		OperandCount:   0,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xF6: Instruction{
		Mnemonic:       "IDLPD",
		ByteLength:     1,
		OperandCount:   0,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xF7: Instruction{
		Mnemonic:       "TRAP",
		ByteLength:     1,
		OperandCount:   0,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xF8: Instruction{
		Mnemonic:       "CLRC",
		ByteLength:     1,
		OperandCount:   0,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xF9: Instruction{
		Mnemonic:       "SETC",
		ByteLength:     1,
		OperandCount:   0,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xFA: Instruction{
		Mnemonic:       "DI",
		ByteLength:     1,
		OperandCount:   0,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xFB: Instruction{
		Mnemonic:       "EI",
		ByteLength:     1,
		OperandCount:   0,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xFC: Instruction{
		Mnemonic:       "CLRVT",
		ByteLength:     1,
		OperandCount:   0,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xFD: Instruction{
		Mnemonic:       "NOP",
		ByteLength:     1,
		OperandCount:   0,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0xFE: Instruction{
		Mnemonic:       "(Note 2) Prefix for signed multiplication and division.",
		ByteLength:     1,
		OperandCount:   0,
		AddressingMode: "",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         true,
		Signed:         false,
		Reserved:       false,
	},
	0xFF: Instruction{
		Mnemonic:       "RST",
		ByteLength:     1,
		OperandCount:   0,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         true,
		Signed:         false,
		Reserved:       false,
	},
}

var instructionsSigned = map[byte]Instruction{
	0x4C: Instruction{
		Mnemonic:       "MUL",
		ByteLength:     5,
		OperandCount:   3,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         true,
		Reserved:       false,
	},
	0x4D: Instruction{
		Mnemonic:       "MUL",
		ByteLength:     6,
		OperandCount:   3,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         true,
		Reserved:       false,
	},
	0x4E: Instruction{
		Mnemonic:       "MUL",
		ByteLength:     5,
		OperandCount:   3,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         true,
		Reserved:       false,
	},
	0x4F: Instruction{
		Mnemonic:       "MUL",
		ByteLength:     6, //6/7
		OperandCount:   3,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         true,
		Reserved:       false,
	},
	0x5C: Instruction{
		Mnemonic:       "MULB",
		ByteLength:     5,
		OperandCount:   3,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         true,
		Reserved:       false,
	},
	0x5D: Instruction{
		Mnemonic:       "MULB",
		ByteLength:     5,
		OperandCount:   3,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x5E: Instruction{
		Mnemonic:       "MULB",
		ByteLength:     5,
		OperandCount:   3,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         false,
		Reserved:       false,
	},
	0x5F: Instruction{
		Mnemonic:       "MULB",
		ByteLength:     6, //6/7
		OperandCount:   3,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         true,
		Reserved:       false,
	},
	0x6C: Instruction{
		Mnemonic:       "MUL",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         true,
		Reserved:       false,
	},
	0x6D: Instruction{
		Mnemonic:       "MUL",
		ByteLength:     5,
		OperandCount:   2,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         true,
		Reserved:       false,
	},
	0x6E: Instruction{
		Mnemonic:       "MUL",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         true,
		Reserved:       false,
	},
	0x6F: Instruction{
		Mnemonic:       "MUL",
		ByteLength:     5, //5/6
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         true,
		Reserved:       false,
	},
	0x7C: Instruction{
		Mnemonic:       "MULB",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         true,
		Reserved:       false,
	},
	0x7D: Instruction{
		Mnemonic:       "MULB",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         true,
		Reserved:       false,
	},
	0x7E: Instruction{
		Mnemonic:       "MULB",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         true,
		Reserved:       false,
	},
	0x7F: Instruction{
		Mnemonic:       "MULB",
		ByteLength:     5, //5/6
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         true,
		Reserved:       false,
	},
	0x8C: Instruction{
		Mnemonic:       "DIV",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         true,
		Reserved:       false,
	},
	0x8D: Instruction{
		Mnemonic:       "DIV",
		ByteLength:     5,
		OperandCount:   2,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         true,
		Reserved:       false,
	},
	0x8E: Instruction{
		Mnemonic:       "DIV",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         true,
		Reserved:       false,
	},
	0x8F: Instruction{
		Mnemonic:       "DIV",
		ByteLength:     5, //5/6
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         true,
		Reserved:       false,
	},
	0x9C: Instruction{
		Mnemonic:       "DIVB",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "direct",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         true,
		Reserved:       false,
	},
	0x9D: Instruction{
		Mnemonic:       "DIVB",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "immediate",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         true,
		Reserved:       false,
	},
	0x9E: Instruction{
		Mnemonic:       "DIVB",
		ByteLength:     4,
		OperandCount:   2,
		AddressingMode: "indirect",
		Description:    "",
		VariableLength: false,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         true,
		Reserved:       false,
	},
	0x9F: Instruction{
		Mnemonic:       "DIVB",
		ByteLength:     5, //5/6
		OperandCount:   2,
		AddressingMode: "indexed",
		Description:    "",
		VariableLength: true,
		AutoIncrement:  false,
		Flags:          Flags{},
		Ignore:         false,
		Signed:         true,
		Reserved:       false,
	},
}
